spring:
  application:
    name: ingestion-service

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always